# Data
path: C:\Users\dokov\Documents\Uni\HiWi\Keytool\data
train: images\train  # train images (relative to 'path')
val: images\val  # val images (relative to 'path')

# Keypoints
kpt_shape: [2, 2]  # [number of keypoints, number of dim]
flip_idx: [0, 1]

# Classes
names:
  0: keytool